### ISSUE TITLE
[BUG] Crawling for NCBI doesn't work properly.

### ISSUE THREAD

**Issue by hikarinotomadoi** [iwasakishuto/Translation-Gummy#15]
**Describe the bug**
Crawling for NCBI doesn't work properly.

**To Reproduce**
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3682417/
This paper is archived in PMC.
Translate this paper as below.
```py
from gummy import TranslationGummy
from gummy.utils import get_driver
with get_driver() as driver:          
    model = TranslationGummy(driver=driver, translator="deepl", gateway="useless")
    pdf_path = model.toPDF(url="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3682417/")
    print(pdf_path)
```

**Expected behavior**
All the main texts are translated.

**Screenshots**
Only "Supplementary Material" and "Acknowledgments" are translated.

**Comment by hikarinotomadoi** [comment]
Guessing from this implementation, some papers may have different format from the paper shown in above even if both of them are PMC archived paper, so I think there should be some test cases for each journals.
https://github.com/iwasakishuto/Translation-Gummy/blob/53831970820bac86d4fcb3c6b10087eadf8051d1/gummy/journals.py#L477

**Comment by iwasakishuto** [comment]
Thank you for pointing out. It is very hard and difficult to check all patterns, so it would help a lot if you teach me. In this case, I decided to use the **text** written in the `<h2>` tag instead of **id** of `<h2>`.

https://github.com/iwasakishuto/Translation-Gummy/blob/63dbb71d5b4bdd91aaf49719d574618d0e5315da/gummy/journals.py#L489

In addition to that, I added test cases. Thank you very much again.
