### ISSUE TITLE
[REQUEST] process References

### ISSUE THREAD

**Issue by hikarinotomadoi** [iwasakishuto/Translation-Gummy#19]
References in the main text sometimes cause wrong translations.
For example translating [this paper's](https://onlinelibrary.wiley.com/doi/full/10.1002/pro.2899) introduction.

Removing these reference link tags or processing it separately and make it appear in the final PDF as a link to a paper will be great.

**Comment by iwasakishuto** [comment]
Thank you for your great suggestion. I'm using `gummy.journals.GummyAbstJournal.decompose_soup_tags` to remove those reference link tags because they are often surrounded by `<sup>` or `<sub>` tags. However, the texts in `<sup>` and `<sub>` can have an important meanings, so if there is another good removal method (e.g. remove only texts in `<sup><a>` or `<sub><a>`), I would like to adopt it.
